# Generated by Django 5.0.6 on 2024-05-10 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='liked',
        ),
        migrations.AlterField(
            model_name='test',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 0, 29, 48, 356914, tzinfo=datetime.timezone.utc)),
        ),
    ]
